'use strict';
const $=s=>document.querySelector(s);let data,selected=1,timer;
const labels=['Q1 · Setup visible','Q2 · Intervention visible','Q3 · Physical response present','Q4 · Condition following','Q5 · Causal order','Q6 · Anchors preserved','Q7 · No physical artifacts','Q8 · Judgeable'];
function text(tag,value,cls){const e=document.createElement(tag);e.textContent=value;if(cls)e.className=cls;return e}
function render(){const mode=$('#condition').value;const a=data.judges.muse[mode].judgment,b=data.judges.gpt[mode].judgment;const keys=Object.keys(a.q_scores);$('#questions').replaceChildren();keys.forEach((k,i)=>{const tr=document.createElement('tr');tr.className=(i===selected?'active ':'')+(a.q_scores[k]!==b.q_scores[k]?'different':'');const td=document.createElement('td'),button=text('button',labels[i]);button.type='button';button.setAttribute('aria-pressed',String(i===selected));button.onclick=()=>{selected=i;render()};td.append(button);tr.append(td,text('td',a.q_scores[k].toFixed(2),'muse'),text('td',b.q_scores[k].toFixed(2),'gpt'));$('#questions').append(tr)});$('#reasons').replaceChildren();for(const [name,j,cls] of [['MuseGlimmer',a,'muse'],['GPT',b,'gpt']]){const box=document.createElement('div');box.className='judge-box';box.append(text('h3',name+' · '+labels[selected],cls),text('p',j.reasons[keys[selected]]));$('#reasons').append(box)}}
function showFrame(){const n=Number($('#frame').value);$('#sequence-image').src=`assets/frame-${n}.jpg`;$('#sequence-image').alt=`Video frame ${n} at ${(n/24).toFixed(3)} seconds`;$('#frame-label').textContent=`${n} · ${(n/24).toFixed(3)} s · ${n===0||n===8?'supplied to judges':'not supplied to judges'}`}
function stop(){clearInterval(timer);timer=null;$('#play-sequence').textContent='Play intervening frames slowly'}
$('#frame').oninput=()=>{stop();showFrame()};$('#play-sequence').onclick=()=>{if(timer){stop();return}$('#frame').value=0;showFrame();$('#play-sequence').textContent='Pause';timer=setInterval(()=>{const n=Number($('#frame').value);if(n===8){stop();return}$('#frame').value=n+1;showFrame()},350)};$('#reset-sequence').onclick=()=>{stop();$('#frame').value=0;showFrame()};
function recalc(){const grounding=$('#swap-q2').checked?.875:.625,judgeable=$('#swap-q8').checked?1:.75;$('#counterfactual').textContent=(grounding*judgeable*.736875).toFixed(6);$('#counter-formula').textContent=`${grounding.toFixed(3)} × ${judgeable.toFixed(3)} × 0.736875`}
$('#swap-q2').onchange=recalc;$('#swap-q8').onchange=recalc;$('#condition').onchange=render;
fetch('data.json').then(r=>{if(!r.ok)throw Error('Evidence could not be loaded');return r.json()}).then(d=>{data=d;$('#video').src=d.video;render()}).catch(e=>{$('#questions').append(text('tr',e.message))});
